apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # Тип Service, который открывает порт на каждом узле кластера
  selector:
    app: nginx  # Должен совпадать с меткой в Deployment
  ports:
    - protocol: TCP
      port: 80  # Порт, на котором Service будет доступен внутри кластера
      targetPort: 80  # Порт, на который Service будет перенаправлять трафик (должен совпадать с containerPort в Deployment)
      nodePort: 30000  # Порт, который будет открыт на каждом узле кластера (диапазон 30000-32767)
