apiVersion: v1
kind: Service
metadata:
  name: nexus-nodeport
  namespace: nexus-registry
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nexus-repository-manager
    app.kubernetes.io/instance: nexus
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31000
      protocol: TCP
